image: node:latest

before_script:
#  - docker info
  - cd web-installer

stages:
  - build
  - test

cache:
  paths:
    - web-installer/node_modules/

install:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage: test
  # rules:
  #   - if: '$CODE_QUALITY_DISABLED'
  #     when: never
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
  #   - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'      # Run code quality job in pipelines on the master branch (but not in other branch pipelines)
  #   - if: '$CI_COMMIT_TAG'                               # Run code quality job in pipelines for tags
  artifacts:
    paths: [gl-code-quality-report.json]

# test:
#     stage: test
#     script:
#         - npm install
#         - npm test
