image: node:latest

stages:
    - build
    - test

cache:
    paths:
        - src/web-installer/frontend/node_modules/

install_dependencies:
    stage: build
    script:
        - cd src/web-installer/frontend
        - npm install
        - npm test
    artifacts:
        paths:
        - node_modules/

testing_testing:
    stage: test
    script:
        - cd src/web-installer/frontend/
        - npm test