image: node:latest

before_script:
    - cd 'src/web-installer/frontend/'

stages:
    - test

run-unit-test:
    stage: test
    script:
        - npm install # Install all dependencies
        - npm test # Test 