image: node:latest

before_script:
    - cd web-installer

stages:
    - build
    - test

cache:
    paths:
        - web-installer/node_modules/

install:
    stage: build
    script:
        - npm install
    artifacts:
        paths:
        - node_modules/

test:
    stage: test
    script:
        - npm install
        - npm test