image: node:latest

before_script:
    - cd src/web-installer

stages:
    - build

cache:
    paths:
        - src/web-installer/node_modules/

install:
    stage: build
    script:
        - npm install
    artifacts:
        paths:
        - node_modules/

test:
    stage: test
    script:
        - npm install
        - npm test