version: '3.7'

services:
  installer:
    environment:
      - 'ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}'
      - 'ACCESS_TOKEN_LIFE=${ACCESS_TOKEN_LIFE}'
      - 'REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}'
      - 'REFRESH_TOKEN_LIFE=${REFRESH_TOKEN_LIFE}'
      - 'DB_NAME=${DB_NAME}'
      - 'INSTALLER_USERNAME=${INSTALLER_USERNAME}'
      - 'INSTALLER_PASSWORD=${INSTALLER_PASSWORD}'
      - 'DB_HOST=${DB_HOST}'
      - 'DB_PORT=${DB_PORT}'
      - 'INSTALLER_AUTH_COLLECTION=${INSTALLER_AUTH_COLLECTION}'
      - 'ACCOUNTS_COLLECTION=${ACCOUNTS_COLLECTION}'
    build:
      context: './'
      dockerfile: './web-installer/Dockerfile'
    image: 'simplyvc/panic_installer:1.0.0'
    volumes:
      - './config:/opt/panic/config'
      - './certificates:/opt/panic/certificates'
    ports:
      - '${INSTALLER_PORT}:8000'
    restart: always
    networks:
      panic_net:
        ipv4_address: 172.18.0.3

  mongo:
    image: 'mongo'
    networks:
      panic_net:
        ipv4_address: '${DB_HOST}'
    restart: always

networks:
  panic_net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24